### ISSUE TITLE
Clean up CSS Colors

### ISSUE THREAD

**Issue by chimerror** [chimerror/quoll-issues#12]
During the last release, I played around picking colors with better contrast:

```css
    --ada-cream: #F2E8E1;
    --ada-chocolate: #2C1E19;
    --ada-pink: #FF7BA9;
    --ada-light-purple: #A576C4;
    --ada-dark-purple: #7C5994;
    --ada-gray: #ADA7B0;
```

However, there are several points where I am using other CSS variables for the colors, which have their old values (for example):

```css
body.dark-theme {
    --bg-color: #2C1E19;
    --text-color:#F2E8E1;
    --line-input-bg-color: #F2E8E1;
    --line-input-text-color: #FF7BA9;
    --room-name-text-color: #A576C4;
    --banner-release-text-color: #ADA7B0;
}
```

While I don't think these additional variable names are a bad idea, it would be better to have these fall back to the nice named colors above so the palette stays consistent.
